//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class xBoxScore
{
    public bool Exclude { get; set; }
    public string LeagueName { get; set; }
    public System.DateTime GameDate { get; set; }
    public int RotNum { get; set; }
    public string Team { get; set; }
    public string Opp { get; set; }
    public string Venue { get; set; }
    public string GameTime { get; set; }
    public string Season { get; set; }
    public string SubSeason { get; set; }
    public int MinutesPlayed { get; set; }
    public int OtPeriods { get; set; }
    public int ScoreReg { get; set; }
    public int ScoreRegOpp { get; set; }
    public int ScoreOT { get; set; }
    public int ScoreOTOpp { get; set; }
    public int ScoreQ1 { get; set; }
    public int ScoreQ1Opp { get; set; }
    public int ScoreQ2 { get; set; }
    public int ScoreQ2Opp { get; set; }
    public int ScoreQ3 { get; set; }
    public int ScoreQ3Opp { get; set; }
    public int ScoreQ4 { get; set; }
    public int ScoreQ4Opp { get; set; }
    public int ShotsActualMadeUsPt1 { get; set; }
    public int ShotsActualMadeOppPt1 { get; set; }
    public int ShotsActualAttemptedUsPt1 { get; set; }
    public int ShotsActualAttemptedOppPt1 { get; set; }
    public int ShotsActualMadeUsPt2 { get; set; }
    public int ShotsActualMadeOppPt2 { get; set; }
    public int ShotsActualAttemptedUsPt2 { get; set; }
    public int ShotsActualAttemptedOppPt2 { get; set; }
    public int ShotsActualMadeUsPt3 { get; set; }
    public int ShotsActualMadeOppPt3 { get; set; }
    public int ShotsActualAttemptedUsPt3 { get; set; }
    public int ShotsActualAttemptedOppPt3 { get; set; }
    public double ShotsActualMadeUsRegPt1 { get; set; }
    public double ShotsActualMadeOppRegPt1 { get; set; }
    public double ShotsActualAttemptedUsRegPt1 { get; set; }
    public double ShotsActualAttemptedOppRegPt1 { get; set; }
    public double ShotsActualMadeUsRegPt2 { get; set; }
    public double ShotsActualMadeOppRegPt2 { get; set; }
    public double ShotsActualAttemptedUsRegPt2 { get; set; }
    public double ShotsActualAttemptedOppRegPt2 { get; set; }
    public double ShotsActualMadeUsRegPt3 { get; set; }
    public double ShotsActualMadeOppRegPt3 { get; set; }
    public double ShotsActualAttemptedUsRegPt3 { get; set; }
    public double ShotsActualAttemptedOppRegPt3 { get; set; }
    public int OffRBOpp { get; set; }
    public int OffRB { get; set; }
    public int Assists { get; set; }
    public int TurnOvers { get; set; }
    public int AssistsOpp { get; set; }
    public int TurnOversOpp { get; set; }
    public string Source { get; set; }
    public System.DateTime LoadDate { get; set; }
    public short LoadTimeSeconds { get; set; }
}
