//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Team
{
    public int TeamID { get; set; }
    public int LeagueID { get; set; }
    public string LeagueName { get; set; }
    public string TeamSource { get; set; }
    public string TeamNameInDatabase { get; set; }
    public string TeamName { get; set; }
    public System.DateTime StartDate { get; set; }
}
