//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentOTsideLine
    {
        public string LeagueName { get; set; }
        public double SideLine { get; set; }
        public string AdjOTsideLine { get; set; }
    }
}
