//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisResult
    {
        public int AnalysisResultsID { get; set; }
        public string RunID { get; set; }
        public System.DateTime TS { get; set; }
        public int RunDurationMinutes { get; set; }
        public string LeagueName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Games { get; set; }
        public int Plays { get; set; }
        public double Wins { get; set; }
        public double Losses { get; set; }
        public double WLPct { get; set; }
        public int Unders { get; set; }
        public int Overs { get; set; }
        public double UnderWins { get; set; }
        public double UnderLosses { get; set; }
        public double UnderPct { get; set; }
        public double OverWins { get; set; }
        public double OverLosses { get; set; }
        public double OverPct { get; set; }
        public double AvgScoreReg { get; set; }
        public double AvgScoreRegwOT { get; set; }
        public double AvgTotalLine { get; set; }
        public double AvgOurTotalLine { get; set; }
        public double AvgLineDiffResultReg { get; set; }
        public double DefaultOTamt { get; set; }
        public int GB1 { get; set; }
        public int GB2 { get; set; }
        public int GB3 { get; set; }
        public int WeightGB1 { get; set; }
        public int WeightGB2 { get; set; }
        public int WeightGB3 { get; set; }
        public int Threshold { get; set; }
        public double BxScLinePct { get; set; }
        public double BxScTmStrPct { get; set; }
        public double TmStrAdjPct { get; set; }
        public bool BothHome_Away { get; set; }
        public string Description { get; set; }
    }
}
