//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BballEntities1 : DbContext
    {
        public BballEntities1()
            : base("name=BballEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdjustmentsCodes> AdjustmentsCodes { get; set; }
        public virtual DbSet<DailySummary> DailySummary { get; set; }
        public virtual DbSet<Adjustments> Adjustments { get; set; }
        public virtual DbSet<AdjustmentsDaily> AdjustmentsDaily { get; set; }
        public virtual DbSet<BoxScores> BoxScores { get; set; }
        public virtual DbSet<Lines> Lines { get; set; }
        public virtual DbSet<SeasonInfo> SeasonInfo { get; set; }
        public virtual DbSet<ParmTable> ParmTables { get; set; }
        public virtual DbSet<BoxScoresLast5Min> BoxScoresLast5Min { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Rotation> Rotation { get; set; }
    }
}
