//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxScoresAdjusted
    {
        public int BoxScoresAdjustedID__BoxScoresAdjustedID__BoxScoresAdjustedID { get; set; }
        public string LeagueName { get; set; }
        public System.DateTime GameDate { get; set; }
        public int RotNum { get; set; }
        public string Team { get; set; }
        public string Opp { get; set; }
        public string Venue { get; set; }
        public double BxScLinePct { get; set; }
        public double BxScTmStrPct { get; set; }
        public double Curve2LinePctUs { get; set; }
        public double OppTmStrPctUs { get; set; }
        public Nullable<double> TmTLUs { get; set; }
        public double ScoreRegUs { get; set; }
        public Nullable<double> TeamStrengthBxScAdjPctAllowed { get; set; }
        public double ShotsMadeUsRegPt1 { get; set; }
        public Nullable<double> Q4Last1MinUsPt1 { get; set; }
        public double StatLastMinAdjUsPt1 { get; set; }
        public double AdjustedMadeUsPt1 { get; set; }
        public double ShotsMadeUsRegPt2 { get; set; }
        public Nullable<double> Q4Last1MinUsPt2 { get; set; }
        public double StatLastMinAdjUsPt2 { get; set; }
        public double AdjustedMadeUsPt2 { get; set; }
        public double ShotsMadeUsRegPt3 { get; set; }
        public Nullable<double> Q4Last1MinUsPt3 { get; set; }
        public double StatLastMinAdjUsPt3 { get; set; }
        public double AdjustedMadeUsPt3 { get; set; }
        public double Curve2LinePctOp { get; set; }
        public double OppTmStrPctOp { get; set; }
        public Nullable<double> TmTLOP { get; set; }
        public double ScoreRegOp { get; set; }
        public Nullable<double> TeamStrengthBxScAdjPctScored { get; set; }
        public double ShotsMadeOpRegPt1 { get; set; }
        public Nullable<double> Q4Last1MinOpPt1 { get; set; }
        public double StatLastMinAdjOpPt1 { get; set; }
        public double AdjustedMadeOpPt1 { get; set; }
        public double ShotsMadeOpRegPt2 { get; set; }
        public Nullable<double> Q4Last1MinOpPt2 { get; set; }
        public double StatLastMinAdjOpPt2 { get; set; }
        public double AdjustedMadeOpPt2 { get; set; }
        public double ShotsMadeOpRegPt3 { get; set; }
        public Nullable<double> Q4Last1MinOpPt3 { get; set; }
        public double StatLastMinAdjOpPt3 { get; set; }
        public double AdjustedMadeOpPt3 { get; set; }
        public double ShotsAttemptedUsRegPt1 { get; set; }
        public double ShotsAttemptedUsRegPt2 { get; set; }
        public double ShotsAttemptedUsRegPt3 { get; set; }
        public double ShotsAttemptedOpRegPt1 { get; set; }
        public double ShotsAttemptedOpRegPt2 { get; set; }
        public double ShotsAttemptedOpRegPt3 { get; set; }
    }
}
