//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxScoresSeed
    {
        public int BoxScoresSeedID { get; set; }
        public string UserName { get; set; }
        public string LeagueName { get; set; }
        public string Season { get; set; }
        public int GamesBack { get; set; }
        public string Team { get; set; }
        public string Venue { get; set; }
        public double AdjustmentAmountMade { get; set; }
        public double AdjustmentAmountAllowed { get; set; }
        public double LastYearMadeTmStr { get; set; }
        public double LastYearShotsMadePt1 { get; set; }
        public double LastYearShotsMadePt2 { get; set; }
        public double LastYearShotsMadePt3 { get; set; }
        public double LastYearAllowedTmStr { get; set; }
        public double LastYearShotsAllowedPt1 { get; set; }
        public double LastYearShotsAllowedPt2 { get; set; }
        public double LastYearShotsAllowedPt3 { get; set; }
        public double ThisYearShotsMadePt1 { get; set; }
        public double ThisYearShotsMadePt2 { get; set; }
        public double ThisYearShotsMadePt3 { get; set; }
        public double ThisYearShotsAllowedPt1 { get; set; }
        public double ThisYearShotsAllowedPt2 { get; set; }
        public double ThisYearShotsAllowedPt3 { get; set; }
        public double PctMadePt1 { get; set; }
        public double PctMadePt2 { get; set; }
        public double PctMadePt3 { get; set; }
        public double PctAllowedPt1 { get; set; }
        public double PctAllowedPt2 { get; set; }
        public double PctAllowedPt3 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
