//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxScoresSeeds
    {
        public int BoxScoresSeedID { get; set; }
        public string UserName { get; set; }
        public string LeagueName { get; set; }
        public string Season { get; set; }
        public int GamesBack { get; set; }
        public string Team { get; set; }
        public double AdjustmentAmountMade { get; set; }
        public double AdjustmentAmountAllowed { get; set; }
        public double AwayShotsMadePt1 { get; set; }
        public double AwayShotsMadePt2 { get; set; }
        public double AwayShotsMadePt3 { get; set; }
        public double AwayShotsAllowedPt1 { get; set; }
        public double AwayShotsAllowedPt2 { get; set; }
        public double AwayShotsAllowedPt3 { get; set; }
        public double AwayShotsAdjustedMadePt1 { get; set; }
        public double AwayShotsAdjustedMadePt2 { get; set; }
        public double AwayShotsAdjustedMadePt3 { get; set; }
        public double AwayShotsAdjustedAllowedPt1 { get; set; }
        public double AwayShotsAdjustedAllowedPt2 { get; set; }
        public double AwayShotsAdjustedAllowedPt3 { get; set; }
        public double HomeShotsMadePt1 { get; set; }
        public double HomeShotsMadePt2 { get; set; }
        public double HomeShotsMadePt3 { get; set; }
        public double HomeShotsAllowedPt1 { get; set; }
        public double HomeShotsAllowedPt2 { get; set; }
        public double HomeShotsAllowedPt3 { get; set; }
        public double HomeShotsAdjustedMadePt1 { get; set; }
        public double HomeShotsAdjustedMadePt2 { get; set; }
        public double HomeShotsAdjustedMadePt3 { get; set; }
        public double HomeShotsAdjustedAllowedPt1 { get; set; }
        public double HomeShotsAdjustedAllowedPt2 { get; set; }
        public double HomeShotsAdjustedAllowedPt3 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
