//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxScoresLast5Min
    {
        public int BoxScoresLast5MinID { get; set; }
        public string LeagueName { get; set; }
        public System.DateTime GameDate { get; set; }
        public int RotNum { get; set; }
        public string Team { get; set; }
        public string Opp { get; set; }
        public string Venue { get; set; }
        public double Q4Last5MinScore { get; set; }
        public double Q4Last1MinScore { get; set; }
        public double Q4Score { get; set; }
        public double Q4Last1MinScoreUs { get; set; }
        public double Q4Last1MinScoreOp { get; set; }
        public string Q4Last1MinWinningTeam { get; set; }
        public double Q4Last1MinUsPt1 { get; set; }
        public double Q4Last1MinUsPt2 { get; set; }
        public double Q4Last1MinUsPt3 { get; set; }
        public double Q4Last1MinOpPt1 { get; set; }
        public double Q4Last1MinOpPt2 { get; set; }
        public double Q4Last1MinOpPt3 { get; set; }
        public string Source { get; set; }
        public System.DateTime LoadDate { get; set; }
    }
}
