//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueInfo
    {
        public string LeagueName { get; set; }
        public System.DateTime StartDate { get; set; }
        public int NumberOfTeams { get; set; }
        public int Periods { get; set; }
        public int MinutesPerPeriod { get; set; }
        public int OverTimeMinutes { get; set; }
        public double DefaultOTamt { get; set; }
        public bool MultiYearLeague { get; set; }
        public string LeagueColor { get; set; }
        public string BoxScoresL5MinURL { get; set; }
    }
}
