//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rotation
    {
        public int RotationID { get; set; }
        public string LeagueName { get; set; }
        public string Season { get; set; }
        public string SubSeason { get; set; }
        public Nullable<int> SubSeasonPeriod { get; set; }
        public System.DateTime GameDate { get; set; }
        public int RotNum { get; set; }
        public string Venue { get; set; }
        public string Team { get; set; }
        public string Opp { get; set; }
        public string GameTime { get; set; }
        public string TV { get; set; }
        public Nullable<double> SideLine { get; set; }
        public Nullable<double> TotalLine { get; set; }
        public Nullable<double> TotalLineTeam { get; set; }
        public Nullable<double> TotalLineOpp { get; set; }
        public Nullable<double> OpenTotalLine { get; set; }
        public string BoxScoreSource { get; set; }
        public string BoxScoreUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Canceled { get; set; }
    }
}
