//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStat
    {
        public string UserName { get; set; }
        public string LeagueName { get; set; }
        public System.DateTime GameDate { get; set; }
        public int RotNum { get; set; }
        public string Team { get; set; }
        public string Opp { get; set; }
        public string Venue { get; set; }
        public string Season { get; set; }
        public string SubSeason { get; set; }
        public Nullable<int> Games { get; set; }
        public Nullable<int> LastSeasonHistoryGames { get; set; }
        public Nullable<System.DateTime> StartGameDate { get; set; }
        public Nullable<double> ShotsAdjustedMadeUsPt1 { get; set; }
        public Nullable<double> ShotsAdjustedMadeUsPt2 { get; set; }
        public Nullable<double> ShotsAdjustedMadeUsPt3 { get; set; }
        public Nullable<double> ShotsAdjustedMadeOppPt1 { get; set; }
        public Nullable<double> ShotsAdjustedMadeOppPt2 { get; set; }
        public Nullable<double> ShotsAdjustedMadeOppPt3 { get; set; }
        public Nullable<double> TeamStrengthUs { get; set; }
        public Nullable<double> TeamStrengthOpp { get; set; }
        public Nullable<double> TeamStrength { get; set; }
    }
}
