//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStatsAverage
    {
        public string UserName { get; set; }
        public string LeagueName { get; set; }
        public System.DateTime GameDate { get; set; }
        public int RotNum { get; set; }
        public string Team { get; set; }
        public string Venue { get; set; }
        public int GB { get; set; }
        public Nullable<int> ActualGB { get; set; }
        public System.DateTime StartGameDate { get; set; }
        public Nullable<System.DateTime> EndGameDate { get; set; }
        public Nullable<double> AverageMadeUs { get; set; }
        public Nullable<double> AverageMadeOp { get; set; }
        public Nullable<double> AverageAdjustedScoreRegUs { get; set; }
        public Nullable<double> AverageAdjustedScoreRegOp { get; set; }
        public Nullable<double> CalcScoredDiffUs { get; set; }
        public Nullable<double> CalcScoredDiffOp { get; set; }
        public double AverageMadeUsPt1 { get; set; }
        public double AverageMadeUsPt2 { get; set; }
        public double AverageMadeUsPt3 { get; set; }
        public double AverageMadeOpPt1 { get; set; }
        public double AverageMadeOpPt2 { get; set; }
        public double AverageMadeOpPt3 { get; set; }
        public Nullable<double> AverageAtmpUsPt1 { get; set; }
        public Nullable<double> AverageAtmpUsPt2 { get; set; }
        public Nullable<double> AverageAtmpUsPt3 { get; set; }
        public Nullable<double> AverageAtmpOpPt1 { get; set; }
        public Nullable<double> AverageAtmpOpPt2 { get; set; }
        public Nullable<double> AverageAtmpOpPt3 { get; set; }
        public Nullable<double> PtsScoredPctPt1 { get; set; }
        public Nullable<double> PtsScoredPctPt2 { get; set; }
        public Nullable<double> PtsScoredPctPt3 { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
    }
}
