//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodaysMatchupsResult
    {
        public int MatchupsResultsID { get; set; }
        public string UserName { get; set; }
        public string LeagueName { get; set; }
        public System.DateTime GameDate { get; set; }
        public string Season { get; set; }
        public string SubSeason { get; set; }
        public int RotNum { get; set; }
        public string TeamAway { get; set; }
        public string TeamHome { get; set; }
        public double OurTotalLine { get; set; }
        public Nullable<double> SideLine { get; set; }
        public Nullable<double> TotalLine { get; set; }
        public Nullable<double> OpenTotalLine { get; set; }
        public Nullable<double> PlayDiff { get; set; }
        public Nullable<double> OpenPlayDiff { get; set; }
        public string Play { get; set; }
        public string PlayResult { get; set; }
        public int UnderWin { get; set; }
        public int UnderLoss { get; set; }
        public int OverWin { get; set; }
        public int OverLoss { get; set; }
        public string TotalDirection { get; set; }
        public string TotalDirectionReg { get; set; }
        public Nullable<double> LineDiffResultReg { get; set; }
        public int MinutesPlayed { get; set; }
        public int OtPeriods { get; set; }
        public double ScoreReg { get; set; }
        public double ScoreOT { get; set; }
        public double ScoreRegHome { get; set; }
        public double ScoreRegAway { get; set; }
        public Nullable<double> VolatilityAway { get; set; }
        public Nullable<double> VolatilityHome { get; set; }
        public Nullable<double> VolatilityGame { get; set; }
        public double BxScLinePct { get; set; }
        public double TmStrAdjPct { get; set; }
        public int GB1 { get; set; }
        public int GB2 { get; set; }
        public int GB3 { get; set; }
        public int WeightGB1 { get; set; }
        public int WeightGB2 { get; set; }
        public int WeightGB3 { get; set; }
        public Nullable<double> AwayGB1 { get; set; }
        public Nullable<double> AwayGB2 { get; set; }
        public Nullable<double> AwayGB3 { get; set; }
        public Nullable<double> HomeGB1 { get; set; }
        public Nullable<double> HomeGB2 { get; set; }
        public Nullable<double> HomeGB3 { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
        public string TeamWinning { get; set; }
        public string TeamLosing { get; set; }
    }
}
