//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodaysPlaysData
    {
        public int TodaysPlaysID { get; set; }
        public Nullable<int> TranType { get; set; }
        public System.DateTime PlayDate { get; set; }
        public string LeagueName { get; set; }
        public int RotNum { get; set; }
        public System.TimeSpan GameTime { get; set; }
        public string TeamAway { get; set; }
        public string TeamHome { get; set; }
        public string PlayType { get; set; }
        public string UO { get; set; }
        public decimal Line { get; set; }
        public string Info { get; set; }
        public decimal PlayAmount { get; set; }
        public decimal PlayWeight { get; set; }
        public decimal Juice { get; set; }
        public string Out { get; set; }
        public string Author { get; set; }
        public string Result { get; set; }
        public Nullable<bool> OT { get; set; }
        public Nullable<int> FinalScore { get; set; }
        public Nullable<decimal> ResultAmount { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
