//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTILog
    {
        public int TTILog_ID { get; set; }
        public System.DateTime TS { get; set; }
        public string UserName { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<int> MessageNum { get; set; }
        public string MessageType { get; set; }
        public string MessageText { get; set; }
        public string CallStack { get; set; }
    }
}
