//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BballMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeagueParms
    {
        public int UserLeagueParmsID { get; set; }
        public string UserName { get; set; }
        public string LeagueName { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool TempRow { get; set; }
        public System.DateTime LgAvgStartDate { get; set; }
        public int LgAvgGamesBack { get; set; }
        public int TeamAvgGamesBack { get; set; }
        public int TeamPaceGamesBack { get; set; }
        public int TeamStrengthGamesBack { get; set; }
        public int VolatilityGamesBack { get; set; }
        public int TeamSeedGames { get; set; }
        public int LoadRotationDaysAhead { get; set; }
        public int GB1 { get; set; }
        public int GB2 { get; set; }
        public int GB3 { get; set; }
        public double WeightGB1 { get; set; }
        public double WeightGB2 { get; set; }
        public double WeightGB3 { get; set; }
        public double Threshold { get; set; }
        public double BxScLinePct { get; set; }
        public double BxScTmStrPct { get; set; }
        public double TmStrAdjPct { get; set; }
        public double TodaysMUPsOppAdjPctPt1 { get; set; }
        public double TodaysMUPsOppAdjPctPt2 { get; set; }
        public double TodaysMUPsOppAdjPctPt3 { get; set; }
        public double RecentLgHistoryAdjPct { get; set; }
        public double TeamPaceAdjPct { get; set; }
        public double TeamAdjPct { get; set; }
        public bool BothHome_Away { get; set; }
        public bool BoxscoresSpanSeasons { get; set; }
    }
}
