using System;

namespace BballMVC.IDTOs
{
   public interface ITodaysMatchupsDTO
   {
      double AdjAmt { get; set; }
      double AdjAmtAway { get; set; }
      double AdjAmtHome { get; set; }
      double AdjDbAway { get; set; }
      double AdjDbHome { get; set; }
      double AdjOTwithSide { get; set; }
      double? AdjPaceAway { get; set; }
      double? AdjPaceHome { get; set; }
      double? AdjRecentLeagueHistory { get; set; }
      double? AdjTeamAway { get; set; }
      double? AdjTeamHome { get; set; }
      double AdjTV { get; set; }
      double? AdjustedDiff { get; set; }
      string AllAdjustmentLines { get; set; }
      double? AverageMadeAwayGB1Pt1 { get; set; }
      double? AverageMadeAwayGB1Pt2 { get; set; }
      double? AverageMadeAwayGB1Pt3 { get; set; }
      double? AverageMadeAwayGB2Pt1 { get; set; }
      double? AverageMadeAwayGB2Pt2 { get; set; }
      double? AverageMadeAwayGB2Pt3 { get; set; }
      double? AverageMadeAwayGB3Pt1 { get; set; }
      double? AverageMadeAwayGB3Pt2 { get; set; }
      double? AverageMadeAwayGB3Pt3 { get; set; }
      double? AverageMadeHomeGB1Pt1 { get; set; }
      double? AverageMadeHomeGB1Pt2 { get; set; }
      double? AverageMadeHomeGB1Pt3 { get; set; }
      double? AverageMadeHomeGB2Pt1 { get; set; }
      double? AverageMadeHomeGB2Pt2 { get; set; }
      double? AverageMadeHomeGB2Pt3 { get; set; }
      double? AverageMadeHomeGB3Pt1 { get; set; }
      double? AverageMadeHomeGB3Pt2 { get; set; }
      double? AverageMadeHomeGB3Pt3 { get; set; }
      int? AwayActualGB1 { get; set; }
      int? AwayActualGB2 { get; set; }
      int? AwayActualGB3 { get; set; }
      int? AwayActualGBTeam { get; set; }
      double? AwayAverageAllowedPt1 { get; set; }
      double? AwayAverageAllowedPt2 { get; set; }
      double? AwayAverageAllowedPt3 { get; set; }
      double AwayAverageAtmpUsPt1 { get; set; }
      double AwayAverageAtmpUsPt2 { get; set; }
      double AwayAverageAtmpUsPt3 { get; set; }
      double? AwayAverageMadePt1 { get; set; }
      double? AwayAverageMadePt2 { get; set; }
      double? AwayAverageMadePt3 { get; set; }
      double? AwayAveragePtsAllowed { get; set; }
      double? AwayAveragePtsScored { get; set; }
      double AwayGB1 { get; set; }
      double AwayGB1Pt1 { get; set; }
      double AwayGB1Pt2 { get; set; }
      double AwayGB1Pt3 { get; set; }
      double AwayGB2 { get; set; }
      double AwayGB2Pt1 { get; set; }
      double AwayGB2Pt2 { get; set; }
      double AwayGB2Pt3 { get; set; }
      double AwayGB3 { get; set; }
      double AwayGB3Pt1 { get; set; }
      double AwayGB3Pt2 { get; set; }
      double AwayGB3Pt3 { get; set; }
      double? AwayProjectedAtmpPt1 { get; set; }
      double? AwayProjectedAtmpPt2 { get; set; }
      double? AwayProjectedAtmpPt3 { get; set; }
      double AwayProjectedPt1 { get; set; }
      double AwayProjectedPt2 { get; set; }
      double AwayProjectedPt3 { get; set; }
      double BxScLinePct { get; set; }
      double? CalcAwayGB1PlanB { get; set; }
      double? CalcAwayGB2PlanB { get; set; }
      double? CalcAwayGB3PlanB { get; set; }
      double? CalcHomeGB1PlanB { get; set; }
      double? CalcHomeGB2PlanB { get; set; }
      double? CalcHomeGB3PlanB { get; set; }
      bool? Canceled { get; set; }
      DateTime GameDate { get; set; }
      string GameTime { get; set; }
      int GB1 { get; set; }
      int GB2 { get; set; }
      int GB3 { get; set; }
      int? HomeActualGB1 { get; set; }
      int? HomeActualGB2 { get; set; }
      int? HomeActualGB3 { get; set; }
      int? HomeActualGBTeam { get; set; }
      double? HomeAverageAllowedPt1 { get; set; }
      double? HomeAverageAllowedPt2 { get; set; }
      double? HomeAverageAllowedPt3 { get; set; }
      double HomeAverageAtmpUsPt1 { get; set; }
      double HomeAverageAtmpUsPt2 { get; set; }
      double HomeAverageAtmpUsPt3 { get; set; }
      double? HomeAverageMadePt1 { get; set; }
      double? HomeAverageMadePt2 { get; set; }
      double? HomeAverageMadePt3 { get; set; }
      double? HomeAveragePtsAllowed { get; set; }
      double? HomeAveragePtsScored { get; set; }
      double HomeGB1 { get; set; }
      double HomeGB1Pt1 { get; set; }
      double HomeGB1Pt2 { get; set; }
      double HomeGB1Pt3 { get; set; }
      double HomeGB2 { get; set; }
      double HomeGB2Pt1 { get; set; }
      double HomeGB2Pt2 { get; set; }
      double HomeGB2Pt3 { get; set; }
      double HomeGB3 { get; set; }
      double HomeGB3Pt1 { get; set; }
      double HomeGB3Pt2 { get; set; }
      double HomeGB3Pt3 { get; set; }
      double? HomeProjectedAtmpPt1 { get; set; }
      double? HomeProjectedAtmpPt2 { get; set; }
      double? HomeProjectedAtmpPt3 { get; set; }
      double HomeProjectedPt1 { get; set; }
      double HomeProjectedPt2 { get; set; }
      double HomeProjectedPt3 { get; set; }
      string LeagueName { get; set; }
      double? LgAvgShotsMadeAwayPt1 { get; set; }
      double? LgAvgShotsMadeAwayPt2 { get; set; }
      double? LgAvgShotsMadeAwayPt3 { get; set; }
      double? LgAvgShotsMadeHomePt1 { get; set; }
      double? LgAvgShotsMadeHomePt2 { get; set; }
      double? LgAvgShotsMadeHomePt3 { get; set; }
      double? OpenPlayDiff { get; set; }
      double? OpenTotalLine { get; set; }
      double OurTotalLine { get; set; }
      double OurTotalLineAway { get; set; }
      double OurTotalLineHome { get; set; }
      string Play { get; set; }
      double? PlayDiff { get; set; }
      string Played { get; set; }
      int RotNum { get; set; }
      string Season { get; set; }
      double SideLine { get; set; }
      string SubSeason { get; set; }
      string TeamAway { get; set; }
      string TeamHome { get; set; }
      string TeamRecordAway { get; set; }
      string TeamRecordHome { get; set; }
      int Threshold { get; set; }
      double? TMoppAdjPct { get; set; }
      double TmStrAdjPct { get; set; }
      double TmStrAway { get; set; }
      double? TmStrHome { get; set; }
      int TodaysMatchupsID { get; set; }
      double? TotalBubbleAway { get; set; }
      double? TotalBubbleHome { get; set; }
      double? TotalLine { get; set; }
      DateTime? TS { get; set; }
      string TV { get; set; }
      double UnAdjTotal { get; set; }
      double? UnAdjTotalAway { get; set; }
      double? UnAdjTotalAwayPlanB { get; set; }
      double UnAdjTotalHome { get; set; }
      double? UnAdjTotalHomePlanB { get; set; }
      double? UnAdjTotalPlanB { get; set; }
      string UserName { get; set; }
      double? Volatility { get; set; }
      double? VolatilityAway { get; set; }
      double? VolatilityHome { get; set; }
      int WeightGB1 { get; set; }
      int WeightGB2 { get; set; }
      int WeightGB3 { get; set; }
   }
}